Repository makeitMVPadmin/P3Forum-, pull requests merged in 2024-04, with the labels that each got.

#1 Fix page route and test push
  package-lock.json
  package.json
  src/App.js
  src/pages/HomePage/HomePage.jsx
Labels: good first issue

#5 Context setup and updated app.js
  package-lock.json
  package.json
  src/App.js
  src/context.jsx
  src/index.js
Labels: enhancement, good first issue

#11 Add timestamp functionality
  src/components/Answers/Answers.jsx
  src/context.jsx
  src/pages/HomePage/HomePage.jsx
Labels: enhancement

#12 PF86 QuestionCard Component
  src/assets/comment.svg
  src/assets/downvote.svg
  src/assets/share.svg
  src/assets/upvote.svg
  src/components/Answers/Answers.jsx
  src/components/Answers/Answers.scss
  src/components/QuestionCard/QuestionCard.jsx
  src/components/QuestionCard/QuestionCard.scss
  src/components/Questions/Questions.jsx
  src/components/Questions/Questions.scss
  src/context.jsx
  src/pages/HomePage/HomePage.jsx
Labels: enhancement, question

#14 Fix question modal
  src/components/Answers/Answers.jsx
  src/components/AskQuestion/AskQuestion.jsx
  src/components/QuestionCard/QuestionCard.jsx
  src/components/QuestionModal/QuestionModal.jsx
  src/context.jsx
  src/pages/HomePage/HomePage.jsx
Labels: Fix Bug

#15 PF86 Avatar Fallback
  src/assets/icons/defaultUser.svg
  src/components/Answers/Answers.scss
  src/components/AskQuestion/AskQuestion.jsx
  src/components/AskQuestion/AskQuestion.scss
  src/components/QuestionCard/QuestionCard.jsx
  src/components/QuestionCard/QuestionCard.scss
  src/components/Questions/Questions.jsx
Labels: enhancement

#18 Pf54 header component dk
  src/assets/calendar.svg
  src/assets/chat.svg
  src/assets/communiti.svg
  src/assets/down_carrot.svg
  src/assets/house.svg
  src/assets/people_chatting.svg
  src/assets/silhouette.svg
  src/components/AskQuestionsContainer/AskQuestionsContainer.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/QuestionModal/QuestionModal.jsx
  src/components/QuestionModal/QuestionModal.scss
  src/pages/ForumHomePage/ForumHomePage.jsx
Labels: enhancement

#19 Fix navigation
  src/App.js
  src/pages/ForumHomePage/ForumHomePage.jsx
Labels: Fix Bug

#20 Style mid-fi Answers Components
  src/components/Answers/Answers.jsx
  src/components/Answers/Answers.scss
Labels: bug, enhancement

#21 Add count to comment icon in QuestionCard
  src/components/Answers/Answers.jsx
  src/components/QuestionCard/QuestionCard.jsx
  src/components/Questions/Questions.jsx
Labels: enhancement

#24 PF70 Communities Component
  src/assets/mock/javascript.svg
  src/assets/mock/mac.svg
  src/assets/mock/project-manage.svg
  src/assets/mock/python.svg
  src/assets/mock/ruby.svg
  src/assets/mock/tux.svg
  src/assets/mock/ux-design.svg
  src/components/AskQuestionsContainer/AskQuestionsContainer.jsx
  src/components/Communities/Communities.jsx
  src/components/Communities/Communities.scss
  src/components/CommunityCard/CommunityCard.jsx
  src/components/CommunityCard/CommunityCard.scss
  src/components/QuestionCard/QuestionCard.scss
  src/components/Sidebar/Sidebar.js
  src/mockData/communitiesData.js
  src/pages/ForumHomePage/ForumHomePage.jsx
Labels: enhancement

#27 Pf118 font matching dk
  src/components/Answers/Answers.jsx
  src/components/Answers/Answers.scss
  src/components/AskQuestion/AskQuestion.scss
  src/components/Communities/Communities.scss
  src/components/CommunityCard/CommunityCard.scss
  src/components/QuestionCard/QuestionCard.scss
  src/components/QuestionModal/QuestionModal.jsx
  src/components/QuestionModal/QuestionModal.scss
  src/components/TopicCard/TopicCard.scss
  src/components/Topics/Topics.scss
  src/pages/ForumHomePage/ForumHomePage.scss
Labels: enhancement

#28 Add Functionality for Dynamic Incrementation of Votes
  src/components/Answers/Answers.jsx
  src/components/QuestionCard/QuestionCard.jsx
  src/components/Questions/Questions.jsx
  src/context.jsx
Labels: enhancement

#29 Add advanced functionality for sorting by votes and dates
  src/components/Answers/Answers.jsx
  src/components/Answers/Answers.scss
  src/components/Questions/Questions.jsx
  src/context.jsx
Labels: enhancement

#30 Fix clear in QuestionModal
  src/components/AskQuestionsContainer/AskQuestionsContainer.jsx
  src/components/QuestionModal/QuestionModal.jsx
  src/components/Questions/Questions.jsx
Labels: Fix Bug

#31 Pf122 error component
  src/App.js
  src/assets/error-image.png
  src/assets/undo.svg
  src/components/Answers/Answers.scss
  src/components/BadURL/BadURL.jsx
  src/components/BadURL/BadURL.scss
Labels: enhancement
